default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 'gitbucket-slack-development'

test:
  <<: *default
  database: 'gitbucket-slack-test'

production:
  <<: *default
  database: 'gitbucket-slack-production'
